
import './globals.css';
import Nav from './NavStyles';
import * as stylex from "@stylexjs/stylex";

const styles = stylex.create({
  main : {
    padding: 20,
    color : 'black',
    fontFamily: 'Poppins',
    fontWeight: 500
  },
});

export const metadata = {
  title: 'Iqbal',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (

    <html>
      <div {...stylex.props(styles.main)}>
      <Nav/>
      <main >{children}</main>
      </div>
    </html>

  )
}
